services:
  postgres:
    image: postgres:17-alpine3.21
    container_name: review-postgres
    ports:
      - "5432:5432"
    env_file: "../.env.deploy"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped